# ===================================
#  McGunsLoot Configuration
# ===================================

loot-table:
  cooldown: 500   # seconds (Option A)

  items:
    entry0:
      material: DIAMOND
      min: 1
      max: 1
      weight: 5

    entry1:
      material: IRON_INGOT
      min: 2
      max: 6
      weight: 20

    entry2:
      material: GOLD_INGOT
      min: 1
      max: 4
      weight: 15
