# ===================================
#  McGunsLoot Configuration
# ===================================

rewards:
  xp:
    chance: 1.0
    min: 10
    max: 50
    command: "givexp %player% %amount%" # Your custom command
  tokens:
    chance: 1.0
    min: 1
    max: 5
    command: "givetokens %player% %amount%"

tables:
  default:
    cooldown: 500
    items:
      entry0:
        material: DIAMOND
        min: 1
        max: 1
        weight: 5
      entry1:
        material: IRON_INGOT
        min: 2
        max: 6
        weight: 20
      entry2:
        material: GOLD_INGOT
        min: 1
        max: 4
        weight: 15

# Chests are saved here automatically
chests: {}